### ISSUE TITLE
Simplification of business data

### ISSUE THREAD

**Issue by aPissarek** [Polewska/webapp22-Polewska#3]
In order to reduce complexity overhead for the management system app, would it be possible to simplify some of the data? For instance, is the sex information 'male'/'female' really necessary or could we drop this? The reason I am asking this is because this information is not used anywhere as far as I can tell and I would imagine it to be of little relevance to the app's business.

**Comment by Polewska** [comment]
Since our staff will use the app, it is best that this information stays because it will be helpful when contacting the worker or even referring to them when talking with a client. Our managers don't know every worker and allowing a situation where when talking about a worker one would referer to them as "Ms or Mrs" would sound unprofessional.
