### ISSUE TITLE
Further information about Employee Role

### ISSUE THREAD

**Issue by aPissarek** [Polewska/webapp22-Polewska#4]
May I suggest we drop the employee 'role' information and instead have only regular "employees", which are then assigned to a location as either Manager or Therapist? I would also suggest to drop the cleaners altogether, if that's okay with you? It looks to me like they are not that relevant to this app's business.

My idea for the app, based on the above assumption, is that each resort must have exactly one manager and can have any number of therapists, where an employee may also be both a manager and a therapist at the same time. By assigning an employee to a resort specifically as a manager (rather than just a general "employee"), we could also ensure that each resort has a manager in the first place, which i imagine must be necessary for the day-to-day resort business.

Then, if you want, we could still discuss some constraints as to which of the Employees can be therapists and who can be a manager. For example we could say that:

a) only employees who have skills can be therapists, anyone can be a manager,

or

b) we can add management as a skill and require this in order for someone to be a resort's manager and employees must still have skills as in a).

**Comment by Polewska** [comment]
I like both the a and b Ideas, so if that's fine with you I would leave this decision to you. Choose the one that in your opinion will work best or will be easier to implement. 

Referring to your first question: Yes we could drop the "role" in the employee table, but in such case, It would be best if you could add "manager" and "therapist" to the location table instead of only "employees". So that we could then differentiate between them. I also see your point and agree with dropping the cleaner information.

**Comment by aPissarek** [comment]
In that case, I will go with a) and am I correct to assume that each resort should have exactly 1 manager?

**Comment by Polewska** [comment]
Yes, that is correct. We don't have many stuff members in each resort so having one manager makes it easier for us
